Refactor for fault tolerance and improved speed

diff --git a/photos_exif_date b/photos_exif_date
--- a/photos_exif_date
+++ b/photos_exif_date
@@ -38,5 +38,9 @@ find "$target" -iname '*.jpg' | while IFS= read -r file; do
             sed 's/\([0-9]\{4\}\):\([0-9]\{2\}\):\([0-9]\{2\}\) \(.*\)/\1-\2-\3 \4/'
 
     )
-    echo "$file,$formatted_date"
+    if [ -n "$date" ]; then
+        echo "$file,$formatted_date"
+    else
+        echo "Timestamp missing or invalid: $file $formatted_date" >&2
+    fi
 done
diff --git a/sunrise_sunset_times b/sunrise_sunset_times
--- a/sunrise_sunset_times
+++ b/sunrise_sunset_times
@@ -53,7 +53,12 @@ declare -A unique_dates
 
 while IFS=, read -r file timestamp; do
   date=$(echo "$timestamp" | cut -d " " -f1)
-  unique_dates["$date"]=1
+  # corrupt EXIF data will have generated an empty timestamp, so skip those ones
+  if [ -n "$date" ]; then
+    unique_dates["$date"]=1
+  else
+    echo "Timestamp missing or invalid: $file $timestamp" >&2
+  fi
 done
 
 for date in "${!unique_dates[@]}"; do
